development:
  cloud_name: jacobsmkt
  api_key: '753179979315631'
  api_secret: wCilYvb6lQIEK5XCczX90-uEyVE

production:
  cloud_name: jacobsmkt
  api_key: '753179979315631'
  api_secret: wCilYvb6lQIEK5XCczX90-uEyVE

test:
  cloud_name: jacobsmkt
  api_key: '753179979315631'
  api_secret: wCilYvb6lQIEK5XCczX90-uEyVE