# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db/development
  pool: 5
  username: root
  password: test1234
  #socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db/test
  pool: 5
  username: root
  password: test1234
  #socket: **/opt/local/var/run/mysql5/mysqld.sock**

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db/production
  pool: 5
  username: root
  password: test1234
  #socket: **/opt/local/var/run/mysql5/mysqld.sock**